version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: database
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-password
      MARIADB_DATABASE: balancebook
      MARIADB_USER: myuser
      MARIADB_PASSWORD: myuserpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmy-secret-password" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - balance-book-net

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    extra_hosts:
      - "auth.local:zuErsetzendeIpAdresse"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://database:3306/balancebook
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=myuserpassword
    depends_on:
       mariadb:
          condition: service_healthy
    networks:
      - balance-book-net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - balance-book-net

volumes:
  mariadb_data:

networks:
  balance-book-net:
    name: balance-book-net
