version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: database
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-password
      MARIADB_DATABASE: elinor2
      MARIADB_USER: myuser
      MARIADB_PASSWORD: myuserpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmy-secret-password" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - balance-book-net

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/elinor2
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=myuserpassword
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloakContainerName:8080/realms/elinor-realm
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloakContainerName:8080/realms/elinor-realm/protocol/openid-connect/certs
    depends_on:
      - mariadb
    networks:
      - balance-book-net

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - balance-book-net

volumes:
  mariadb_data:

networks:
  balance-book-net:
